[tool.poetry]
name = "homework"
version = "0.1.0"
description = ""
authors = ["Artur Khamidulliun <artrimskiy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
